//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineGameStore.Entity
{
    using DataAnnotationsExtensions;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Game = new HashSet<Game>();
        }
    
        public long Login { get; set; }
        public long Password { get; set; }
        public string UserName { get; set; }
        [Email(ErrorMessage = "Такой почты не существует")]
        public string Mail { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public decimal Purse { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Game { get; set; }
    }
}
