//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTreaning.ViewModel.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineGameStoreEntities : DbContext
    {
        public OnlineGameStoreEntities()
            : base("name=OnlineGameStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Developer> Developer { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameOfUser> GameOfUser { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemRequirement> SystemRequirement { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
