//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTreaning.ViewModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {

        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Mail { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public decimal Purse { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Role Role { get; set; }
    }
}
